### ISSUE TITLE
Very hard to read

### ISSUE THREAD

**Issue by Juraj-Masiar** [pixelplanetdev/ppfun-captcha#1]
I'm using the default settings with some ignored chars:
```javascript
const {data, text} = svgCaptcha.create({ignoreChars: 'O0o1iltI'});
```
But the results are so hard to read:
![image](https://user-images.githubusercontent.com/6358971/107847480-59b9f280-6dec-11eb-921b-0248ab506e78.png)
![image](https://user-images.githubusercontent.com/6358971/107847495-72c2a380-6dec-11eb-9632-324d391c9461.png)
![image](https://user-images.githubusercontent.com/6358971/107847521-8a019100-6dec-11eb-80d8-00a5b1b50462.png)
I know it should be hard to read for the OCR, but this is a bit too much...

Isn't there a better way? I thought the characters should be just connected, so that they are drawn using single stroke. This is just madness :D

**Comment by pixelplanetdev** [comment]
try something like
```
svgCaptcha.create({
    width: 800,
    height: 500,
    fontSize: 600,
    nodeDeviation: 0.5,
    connectionPathDeviation: 0.5,
  });
```
All those extra options for changing the randomness are pretty much trial and error right now.

**Comment by pixelplanetdev** [comment]
This is also a really simple setting
![yUXp](https://user-images.githubusercontent.com/59449392/107852632-2d18d180-6e12-11eb-8111-a6d6f4fc7303.png)

```
svgCaptcha.create({
    width: 600,
    height: 300,
    fontSize: 220,
    nodeDeviation: 1.0,
    connectionPathDeviation: 1.5,
  });
```

**Comment by Juraj-Masiar** [comment]
Much better! I've tried to many things and nothing helped.
You should update the readme with some useful tips and probably change the default settings.
Thanks for the help!
