### ISSUE TITLE
how to get in touch with you pal?

### ISSUE THREAD

**Issue by pawelpawelski135** [pixelplanetdev/ppfun-captcha#2]
How are ya? is there any chance to get in touch with you in regard of telegram groups about green passes? feel free to email me at pawelpawelski135[at]wp[dot]pl

**Comment by pixelplanetdev** [comment]
Guilded (which is like discord / slack) link is on pixelplanet.fun

Hope you are doing fine. I didn't see that till now cause i don't check out this repo much.
Good luck bro.
