### ISSUE TITLE
svgCaptcha.createCaptcha() is documented, but doesn't exist.

### ISSUE THREAD

**Issue by XfedeX** [pixelplanetdev/ppfun-captcha#3]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**If it is a bug, which version of svg-captcha are you using?**
The latest one.

**What is the current behavior?**
It returns undefined.

**What is the expected behavior?**
It's expected to return a captcha object, like `svgCaptcha.create()` does.

**Comment by XfedeX** [comment]
@pixelplanetdev PR https://github.com/pixelplanetdev/ppfun-captcha/pull/4 fixes this.

**Comment by pixelplanetdev** [comment]
thanks bro,
will check it out
